FROM python:3.12-slim


WORKDIR /app


COPY . /app

COPY requirements.txt /app


# RUN pip install --upgrade pip && pip install -r requirements.txt
RUN pip install --upgrade pip
RUN pip install numpy pandas matplotlib
RUN pip install opencv-contrib-python PyQt5
RUN pip install tensorflow
RUN apt-get update && apt-get install python3-opencv qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libgl1 libsm6 libxext6 libxrender-dev -y && apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

# Command to run your application
CMD ["python", "main.py"]
